version: '3.8'

services:
  mcp-server-openshift:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MCP_TRANSPORT=sse
      - MCP_PORT=3000
      - MCP_HOST=0.0.0.0
      - OPENSHIFT_CONTEXT=${OPENSHIFT_CONTEXT:-}
      - OPENSHIFT_NAMESPACE=${OPENSHIFT_NAMESPACE:-default}
    volumes:
      # Mount OpenShift config if available
      - ${HOME}/.kube:/home/nodejs/.kube:ro
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mcp-openshift.rule=Host(`mcp-openshift.local`)'
      - 'traefik.http.services.mcp-openshift.loadbalancer.server.port=3000'

  # Optional: Add a reverse proxy for production deployment
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - mcp-server-openshift
    profiles:
      - production
